sudo: required
dist: xenial

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libjudy-dev

env: OMP_NUM_THREADS=4

language: c
compiler:
  - g++

script:
  - make test

notifications:
email:
  on_success: never
  on_failure: always
  recipients:
    - atmughrabi@gmail.com
    - atmughra@virginia.edu

branches:
  only:
    - master