#!/usr/bin/tclsh
set PARAMS_SH_DIR /home/cmv6ru/Documents/00_github_repos/00_GLay/00_make/params.sh
set PARAMS_TCL_DIR /home/cmv6ru/Documents/00_github_repos/00_GLay/00_make/params.tcl
set PARAMS_TCL params.tcl
set PARAMS_SH params.sh
set ROOT_DIR /home/cmv6ru/Documents/00_github_repos
set MAKE_DIR 00_make
set APP_DIR 00_GLay
set HOST_DIR 01_host
set DEVICE_DIR 02_device
set BENCH_DIR 03_data
set GIT_VER f98c2f6
set HOST_NAME jaguar
set APP glay
set APP_TEST test_glayGraph_USER_MANAGED
set APP_LANG cpp
set INTEGRATION openmp
set MAKE_NUM_THREADS 32
set GRAPH_DIR /home/cmv6ru/Documents/00_github_repos/00_GLay/03_data
set GRAPH_SUIT TEST
set GRAPH_NAME v51_e1021
set FILE_BIN_TYPE graph.bin
set FILE_BIN /home/cmv6ru/Documents/00_github_repos/00_GLay/03_data/TEST/v51_e1021/graph.bin
set FILE_LABEL /home/cmv6ru/Documents/00_github_repos/00_GLay/03_data/TEST/v51_e1021/
set PULL_PUSH 0
set ALGORITHMS 0
set SORT_TYPE 1
set DATA_STRUCTURES 0
set REORDER_LAYER1 0
set REORDER_LAYER2 0
set REORDER_LAYER3 0
set CACHE_SIZE 5068672 
set ROOT 0
set TOLERANCE 1e-8
set DELTA 800
set NUM_ITERATIONS 1
set NUM_THREADS_PRE 1
set NUM_THREADS_ALGO 1
set NUM_THREADS_KER 1
set NUM_TRIALS 1
set FILE_FORMAT 1
set CONVERT_FORMAT 1
set BIN_SIZE 1000
set INOUT_STATS 0
set MASK_MODE 0
set VIVADO_GUI_FLAG NO
set XILINX_DIR xilinx_project
set UTILS_DIR utils
set UTILS_PERL utils.pl
set UTILS_TCL utils.tcl
set UTILS_SHELL utils.sh
set UTILS_XDC utils.xdc
set IP_DIR_RTL rtl
set IP_DIR_HLS hls
set REPORTS_DIR rpt
set VIVADO_PACKAGE_DIR vivado_glay_kernel.pkg
set VIVADO_SIMULATE_DIR vivado_glay_kernel.sim
set VIVADO_RUN_DIR glay_kernel.run
set VIVADO_BUILD_DIR vivado_glay_kernel.hw_emu
set VIVADO_VMA_DIR vivado_glay_kernel.vma
set VIVADO_EXPORT_DIR glay_kernel.export
set VIVADO_IMPORT_DIR glay_kernel.import
set VIVADO_VIP_DIR vivado_glay_kernel.vip
set APP_DIR_ACTIVE /home/cmv6ru/Documents/00_github_repos/00_GLay/02_device/xilinx_project_glay_kernel_f98c2f6
set VITIS_BUILD_DIR vitis_glay_kernel.pkg
set XILINX_DIR_ACTIVE xilinx_project_glay_kernel_f98c2f6
set UTILS_DIR_ACTIVE vivado_glay_kernel.utils
set IP_DIR_RTL_ACTIVE vivado_glay_kernel.rtl
set IP_DIR_HLS_ACTIVE vivado_glay_kernel.hls
set REPORTS_DIR_ACTIVE vivado_glay_kernel.rpt
set KERNEL_NAME glay_kernel
set DEVICE_INDEX 0
set XCLBIN_PATH /home/cmv6ru/Documents/00_github_repos/00_GLay/02_device/xilinx_project_glay_kernel_f98c2f6/vivado_glay_kernel.hw_emu/glay_kernel_hw_emu.xclbin
set ALVEO U250
set PART xcu250-figd2104-2L-e
set PLATFORM xilinx_u250_gen3x16_xdma_4_1_202210_1
set VIVADO_VER 2023
set DESIGN_FREQ_HZ 250000000  
set XILINX_JOBS_STRATEGY 8
set XILINX_MAX_THREADS 32
set TARGET hw_emu
set XILINX_IMPL_STRATEGY 1
set XILINX_NUM_KERNELS 1
set XILINX_CTRL_MODE USER_MANAGED
set TESTBENCH_MODULE integration
